---
title: "定量研究方法课程介绍"
author: 
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    toc: true
    toc_depth: 5
    toc_float: 
      collapsed: false
      smooth_scroll: false
    number_sections: true
    css: "../../css/styles.css" 

---



## 课程介绍

- 课程性质：必修课程  
- 课程目的：介绍定量研究方法、统计分析方法  
- 主要内容：    
    - 定量分析的研究设计  
    - 主要定量方法介绍：调查法、实验法、二手数据分析  
    - 统计分析的基本原理与应用  
    - 统计分析工具的运用：R语言  
  
## 学习目标  

- 能够提出具体的研究问题，进行研究设计。  
- 能够理解和应用定量研究方法。  
- 能够理解定量研究方法的优点和缺点。  
- 能够理解各种统计方法，并能够选择合适的统计方法分析定量数据。  
- 能熟练使用统计软件对数据进行处理和分析。  
- 能够对统计分析的结果进行解释，了解其社会与政策含义。  
- 能够独立实施研究项目，展示研究成果。  
- 能够初步进行定量分析论文的写作。  

## 先修课程和知识准备

本课程要求学生已经具有一定统计学和定量研究方法基础，在本科阶段至少学习过一门统计学相关课程，例如《社会统计学》《概率论与数理统计》《统计学》《计量经济学》等，至少学习过一门研究方法相关课程，例如《定量研究方法》《社会研究方法》《社会调查》等。

## 课程参考书籍

1. 先修课程和知识参考书籍：  
    - Earl Babbie 社会研究方法（第11版），华夏出版社，2009
    - 尹海洁，李树林 社会统计学（第2版），中国人民大学出版社，2018
1. 研究方法参考书籍（研究方法）：  
    - Remler, D. K., & Van Ryzin, G. G. (2015). Research Methods in Practice: Strategies for Description and Causation (2nd ed.). Thousand Oaks, CA: Sage.  

1. 统计参考书籍（统计分析）：
    - Gelman and Hill, Data Analysis Using Regression and Multilevel/Hierarchical Models, Cambridge University Press, 2006

1. R语言参考书籍（R语言）：  
    - Kabacoff （王小宁等译）R语言实战（第3版），人民邮电出版社，2023  

1. 其他参考书籍
    - Gary King, Robert O. Keohane, Sidney Verda, 社会科学中的研究设计，格致出版社，2014. （KKV）  
    - Miller, G., & Yang, K. (2008). Handbook of Research Methods in Public Administration. New York: Taylor & Francis.   
    - 陈晓萍, 徐淑英, & 樊景立 (Eds.). (2012). 组织与管理研究的实证方法 (第二版.). 北京: 北京大学出版社. 
    
## 课程要求与成绩  
1. 课堂参与（10%）：每次旷课扣5分，课前请假不扣分  
2. 平时作业（50%）：每次作业10分，5-6次共50分，课后下周一中午12点前提交  
3. 课程论文（30%）：复制一篇论文的结果，进行延伸讨论，完成一篇规范的定量分析文章  
4. 口头报告（10%）：对课程论文内容进行口头报告  

- 时间要求：  
  - 第6周之前选好文章并准备好个人课程论文数据  
  - 第15-16周最后两次课进行口头报告  
  - 结课两周后按时提交课程论文（数据、程序、论文）  
- 其他要求：引文规范、避免抄袭。  
- 课外学习内容：预习复习课程内容，阅读学习材料，学习相关软件的操作，完成练习，准备数据，进行数据分析，写作课程论文。  

## 课程计划  
1. 课程介绍  
1. 选题与文献综述  
1. 研究方法与研究设计  
1. 测量与操作化  
1. 抽样  
1. 调查研究  
1. 实验法  
1. 统计软件介绍R  
1. 多元回归模型  
1. Logistic回归  
1. 广义线性模型  
1. 调节效应、中介效应与结构方程  
1. 多层次模型（optional）  
1. 大数据收集与机器学习应用介绍（optional）  

Note：课程计划会根据课程进度，适度调整。

## 课后阅读与作业  
- 课后阅读：  
  - Remler & Van Ryzin, Chapter 1: Research in the Real World.  
  - Remler & Van Ryzin, Chapter 2: Theory, Models, and Research Questions.  
- 选读：  
  - KKV 《社会科学中的研究设计》第1、2章内容  

## 课后作业：  
- Remler & Van Ryzin, Chapter 1: 1.1, 1.3, 1.4.  
- Remler & Van Ryzin, Chapter 2: 2.5, 2.6 (要求解释性选题).
阅读中遇到的问题  



